### ISSUE TITLE
MultiServer Issues

### ISSUE THREAD

**Issue by myte926** [Fuzss/fivefeetsmall#149]
I can't move when I try swimming on servers like hypixel and shotbow This mod doesn't support MultiServer?

**Comment by embeddedt** [comment]
Since a regular 1.12 client/server has no concept of modern swimming, the mod needs to be installed on both client & server to work correctly. In particular, Hypixel (as a vanilla server) is unlikely to work properly with this mod, and you have a high chance of being banned even if it does work, as a regular 1.12 client should not be able to move that fast in water.
