### ISSUE TITLE
Custom Player Model compatibility problem

### ISSUE THREAD

**Issue by AileRozy** [Fuzss/fivefeetsmall#28]
https://www.curseforge.com/minecraft/mc-mods/custom-player-model-cpm

using this mod with Aqua Acrobatics makes player that with custom hitbox got some problem

![2021-02-18_17 16 45](https://user-images.githubusercontent.com/19416768/108337344-fe369d00-720f-11eb-85c7-b0aec45df2af.png)
![2021-02-18_17 16 57](https://user-images.githubusercontent.com/19416768/108337361-0262ba80-7210-11eb-9d22-5d70ed6c8c8e.png)
Player can't sneak while near any blocks, and anything that need player to sneak won't think player is sneaking while pressing it, 
while sneaking, moving close to blocks makes hitbox go back to standing pose but eye height stay at sneaking height.

![2021-02-18_17 17 28](https://user-images.githubusercontent.com/19416768/108337637-4b1a7380-7210-11eb-95e1-814159c61418.png)
![2021-02-18_17 17 43](https://user-images.githubusercontent.com/19416768/108337647-4e156400-7210-11eb-8bde-4d253c62eca9.png)
Swimming hitbox won't change to Aqua Acrobatics style but eye height are fine, not sure this can fix on CPM side of player custom or not,
when swimming head is facing strange angle.

**Comment by V972** [comment]
I want to add more to this issue.

What I observed is that the bounding box gets set to custom values by a model, but doesn't get reset back to normal when either the model is reset to default or the new model doesn't set custom bounding box size.
This problems gets fixed upon re-joining the world.
![2021-03-03_14 53 49](https://user-images.githubusercontent.com/45125685/109808897-f3283780-7c27-11eb-9bc4-7394ccc47836.png)
![2021-03-03_14 53 58](https://user-images.githubusercontent.com/45125685/109808903-f7eceb80-7c27-11eb-8662-54afb87e4967.png)

Also even when the bounding box is smaller than a needed space (e.g. 1,5 block when trying to go under 2, or less than 1 when going into 1 block space) the player still gets treated as if their bounding box is bigger (according to AquaAcrobatics push-out setting.)
![2021-03-03_14 54 57](https://user-images.githubusercontent.com/45125685/109809002-1652e700-7c28-11eb-945b-4af3126334d5.png)
![2021-03-03_14 55 02](https://user-images.githubusercontent.com/45125685/109809013-19e66e00-7c28-11eb-851c-2fda7c321677.png)

**Comment by NikkeiZX** [comment]
I also wanted to add that the issue in the comment above also happens with Changeling/Metamorph mods as well. the only thing that seems to "fix" the issue is if I morph into an entity that is 2 blocks high (like a skeleton, zombie, etc), and then revert back to normal. 

Also, the crawling feature appears to only activate randomly when approaching 1-block tall spaces.

**Comment by dazadazu** [comment]
Are you still using aquaacro? I also use more player models.

**Comment by embeddedt** [comment]
Unfortunately, by design, Aqua Acrobatics is going to be incompatible with a lot of mods that replace the player model; the expectation is that a mostly-vanilla player is in use (to the best of my knowledge). These mods are coded against the assumption that the player doesn't swim, since that never happened in 1.12.

[Morph](https://www.curseforge.com/minecraft/mc-mods/morph) does work without problems for the most part.

**Comment by kappa-maintainer** [comment]
I am trying to add more compatibility to CPM by mixin, and I found it is not impossible
This is CPM's only usage of setEntityBoundingBox: https://github.com/Gamepiaynmo/CustomModel/blob/9dd4bc3031f4f958fdc3b3895ca4c56afa642bba/src/main/java/com/github/gamepiaynmo/custommodel/mixin/PlayerStatureHandler.java#L33
And calling CustomModel.manager.getModelForPlayer(serverPlayer) can check if a player has model enabled
