### ISSUE TITLE
Blocks pushing player in random directions

### ISSUE THREAD

**Issue by democat3457** [Fuzss/fivefeetsmall#29]
https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/issues/602

Apparently it has to do with the "push player out of blocks" config option being on EXACT, so I'm not sure if it's actually a bug or trying to literally push the player out of a block that isn't really inside of one.

**Comment by Fuzss** [comment]
I think I already fixed this a version ago or two. 😅

**Comment by democat3457** [comment]
I'm pretty sure we are using the latest version on cf, 1.3.5

**Comment by Fuzss** [comment]
Yeah it’s fixed in that version, just checked.

**Comment by democat3457** [comment]
oh well

does changing the option from EXACT to approx or standard really matter? what does the option actually do?

**Comment by Fuzss** [comment]
They are very different. The difference between the three options can be seen in the gallery on the project page.

The option was only included as there was an issue with sneaking on top of a half slab when a solid block is directly above you. It's exactly [this](https://github.com/Kaydax/Ido/issues/3) issue (there is even a video linked somewhere).

This happens due to the pushing-out-of-blocks code in Minecraft 1.12 simply not being adapted for some player heights such as 1.5 blocks.
So for the three options in Aqua Acrobatics; `STANDARD` doesn't change anything, `APPROXIMATE` only applies a small hack-fix to the existing 1.12 code, and `EXACT` ports the whole 1.13+ system, which doesn't have such flaws, but is more performance heavy.
