### ISSUE TITLE
Compatibility issues with TickCentral

### ISSUE THREAD

**Issue by Ameranth** [Fuzss/fivefeetsmall#44]
Hello and thank you for your work!

I've recently tried updating to your newer versions, but each of them after `v1.3.5-1.12.2` cause an immediate crash. Since others haven't posted a similar issue and I'm running ~200 mods, I am guessing this is a compatibility problem.

[Here's the log](https://pastebin.com/YmwWE4Xt), which seems to reference `Duplicate method name&signature in class file net/minecraft/block/BlockSoulSand` as the problem. Please let me know if I can help in some way.

Thank you for your time!

**Comment by embeddedt** [comment]
Can you send a modlist?

If you have the bubble column backport mod installed, remove it; it's made redundant by this mod if you enable bubble columns in the config.

**Comment by Ameranth** [comment]
Thank you for the reply, here's my [modlist](https://pastebin.com/hK5RrB0F).

I don't have bubble column backport; I do have futuremc, backportedflora, and coralreefs, but I tried disabling all three to no avail.

**Comment by embeddedt** [comment]
Thanks. I now see why other mod developers tend to force players to reproduce issues with just one or two mods; searching through that list took a while.

I think this is a conflict with TickCentral. It's a known issue on their end. A fix was [proposed](https://github.com/TerminatorNL/TickCentral/pull/8) but hasn't seen much activity in over a year.

At the moment I can only suggest removing TickCentral, unfortunately.

**Comment by Ameranth** [comment]
Thank you, disabling TickCentral solves the issue!

I apologize for this taking a long time; I think some folks don't try to reproduce with fewer mods because they think the author might know the answer quickly, or can ask for further testing. I'd like to think most people would be happy to test further when asked, given that many authors don't bother responding--so thank you very much again!

**Comment by democat3457** [comment]
@embeddedt i encountered a [similar issue](https://github.com/focamacho/DupeFix-Project/issues/96), maybe it could be solved in that manner without a tickcentral update?
(There was also the `java.lang.ClassFormatError: Duplicate method name&signature in class file` error)

I can't really disable TickCentral as LagGoggles is pretty important for a hefty pack like mine.

**Comment by embeddedt** [comment]
That hack works because `EntityPickarang` happens to already [override `onUpdate`](https://github.com/VazkiiMods/Quark/blob/d4504425f3a4e9611991bcd20ac5814042e6b160/src/main/java/vazkii/quark/world/entity/EntityPickarang.java#L175), so an inject can be used. In my case the soul sand and magma classes don't have an `updateTick` method in vanilla, so there is nothing to inject into. I did try it out of curiosity but it didn't work.

The only other solution is to inject into `Block` itself and only run the custom functions if the block is an instance of soul sand or magma, but that would theoretically have a performance penalty and is quite invasive just to work around a buggy ASM transformer from another mod.

Somebody forked the mod and claims to have gotten a fix working [here](https://github.com/brunoxkk0/TickCentral); perhaps you could give that a try. (Unfortunately you wouldn't be able to publish it on CurseForge.)

OT: Are you one of the maintainers of Rebirth of the Night?

**Comment by democat3457** [comment]
Hmm I see, I'll give it a try and maybe I'll even be able to work it in via ModDirector.

(And yes, I am one of the devs for RotN)

**Comment by embeddedt** [comment]
I added a hack to save you guys the trouble. With 1.6.2 there will be a second config file called `aquaacrobatics_core.cfg`; in there you can disable the conflicting mixins and then the rest of the mod will load with TickCentral present.

Note that you'll also want to disable bubble columns in the main config (if they are enabled) as they can't really function without these mixins.

I think this is the best I can do for you for now.

**Comment by Ameranth** [comment]
Thank you very much, the effort is greatly appreciated!

**Comment by democat3457** [comment]
> I added a hack to save you guys the trouble. With 1.6.2 there will be a second config file called `aquaacrobatics_core.cfg`; in there you can disable the conflicting mixins and then the rest of the mod will load with TickCentral present.
> 
> Note that you'll also want to disable bubble columns in the main config (if they are enabled) as they can't really function without these mixins.

Alright, thanks then!
