### ISSUE TITLE
Water in modded biomes not being affected by custom config colors?

### ISSUE THREAD

**Issue by Turkey9002** [Fuzss/fivefeetsmall#48]
I'm not sure if this affects all modded biomes but it definitely seems to affect the Magical Forest biome from Thaumcraft. I was testing on the config to see about changing the water colors on that biome, but only the fog ends up changing color. (This would mean it shouldn't be a problem with the id) I've then used the same configuration on the Ocean biome and the surface changes color like normal. 

![2021-12-24_14 15 47](https://user-images.githubusercontent.com/86805568/147371402-dcf78679-33d2-4ee9-b172-a3b2497eeea2.png)

![2021-12-24_14 16 20](https://user-images.githubusercontent.com/86805568/147371439-ba3820af-d1d7-4b59-a2cf-75fb54835629.png)

![2021-12-24_14 14 23](https://user-images.githubusercontent.com/86805568/147371425-a1fcb7f8-d50d-49b7-a18a-748006003625.png)

![Fog](https://user-images.githubusercontent.com/86805568/147371456-0698dd4a-5acf-4256-a15f-f9b96f657cde.png)

**Comment by embeddedt** [comment]
Thanks, this was caused by Thaumcraft overriding the normal water color logic and not firing the Forge event which I was using to control it. As such, I've now just overriden water color in all cases - there is no longer any easy way for another mod to prevent it. The config should now work as expected.

You can either wait for the next release or download the beta build from [here](https://github.com/Fuzss/aquaacrobatics/actions/runs/1620273404) when it finishes building.

**Comment by Turkey9002** [comment]
@embeddedt I can confirm it's been happening again. I tested with only the latest version of Aqua Acrobatics, Thaumcraft, Baubles and MixinBooter. ^^;

**Comment by embeddedt** [comment]
Interesting, not sure why the previous fix seemed to work in the first place. It should be fixed properly in 1.13.3.

**Comment by Turkey9002** [comment]
It works again now. Thanks for the quick fix!
