### ISSUE TITLE
Glitch with flans mod

### ISSUE THREAD

**Issue by Dan4oby** [Fuzss/fivefeetsmall#87]
You can check out it here:
https://imgur.com/a/A2bGu4A

I dont know if this issue because of this mod or flans. Modular Warfare that adds guns too doesnt make any conflicts.

**Comment by embeddedt** [comment]
Unfortunately it looks like Flans reimplements a lot of the vanilla rendering logic [here](https://github.com/FlansMods/FlansMod/blob/425eee3bdf9a6e93fd087b2656cfbf21e40b1c2e/src/main/java/com/flansmod/client/ClientRenderHooks.java#L412-L532), which will cause issues since Aqua Acrobatics only patches the vanilla renderer. I don't think I can fix this easily on my end, sorry.
